### ISSUE TITLE
Decimal Point Issue. Cannot be used more than once in output display

### ISSUE THREAD

**Issue by ibltrm** [ibltrm/calculator#5]
![issue-decimal](https://user-images.githubusercontent.com/93558685/188247453-5c720322-e785-4e58-8ba3-19ae6fb9aef0.gif)

**Comment by kevinmnm** [comment]
Take a look at `inputDecimal()` function and try to log every single step and value of associated variables. As this bug is occurring because of the incorrect value of `calculator.outputDisplay`, you might want to look at how this function is updating `calculator.outputDisplay`.
